### ISSUE TITLE
Can't handle interfaces

### ISSUE THREAD

**Issue by Niatross** [LogMANOriginal/JSONtext-Object-Serialization#25]
If the user flattens an interface (not a concrete implementation of that interface) to JSON subsequent 'From JSON' calls will return an error.

This is because Compose LabVIEW Object cannot handle an empty variant array (Which is what is returned when you have decomposed an interface)

Solution is to explicitly handle an empty array of variants from Decompose LabVIEW Object

**Comment by logmanoriginal** [comment]
Thanks for reporting this issue.

The issue was addressed in [LabVIEW-Composition V1.3.1](https://github.com/logmanoriginal/LabVIEW-Composition/releases/tag/1.3.1).

Package dependencies were updated in the latest release: [1.0.4](https://github.com/logmanoriginal/JSONtext-Object-Serialization/releases/tag/1.0.4).
